### ISSUE TITLE
Updated Vendor Locations

### ISSUE THREAD

**Issue by josephlei** [code4sac/wicit#37]
I am designing code to notify us when the vendor location data set is updated, however there is no ETA.

For the time being, there is an updated version (2015-05-27) located at the link below.  Can someone please help me locate where/how this data is integrated into the application so in the future I can simply incorporate it as part of my fork and submit a pull request?  Thank You

https://cdph.data.ca.gov/Facilities-and-Services/Women-Infants-and-Children-WIC-Authorized-Vendors/i7wi-ei4m

**Comment by jesserosato** [comment]
Vendor locations are pulled from the data portal as needed. We should always be pulling through the newest data automatically.

—

**Comment by josephlei** [comment]
Awesome.. I'm working off the updating API endpoint as well, don't know the back end workings of WICIT to see where it was integrated thank you.  It is my understanding that the 9 digit unique identifier for datasets should not ever change.  Closing issue.. thanks again
