### ISSUE TITLE
Unable to load nearby locations

### ISSUE THREAD

**Issue by josephlei** [code4sac/wicit#43]
Something broke, locations are no longer displaying on findwic.com

Sorry for opening a bummer issue and not providing a solution to fix it, but yeah.. just putting it out there =\ Can anyone help?

**Comment by jesserosato** [comment]
Hey Joseph,

The code to fix this is on master (the URL for the API we hit for that data changed), I just keep running into roadblocks when I try to actually deploy it on Digital Ocean. I’ll give it another look this weekend and see if I can’t get it back up and running.

On Fri, Jun 24, 2016 at 2:35 PM Joseph

<
mailto:Joseph <notifications@github.com>
> wrote:

Something broke, locations are no longer displaying on findwic.com

Sorry for opening a bummer issue and not providing a solution to fix it, but yeah.. just putting it out there =\ Can anyone help?

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly,
https://github.com/code4sac/wicit/issues/43
, or
https://github.com/notifications/unsubscribe/AD0COO9CRnf-UZlRG0a0KqkLnU_B16BDks5qPE2ZgaJpZM4I-JOl
.

**Comment by joelrip** [comment]
Hey Jesse,

Are you still running into Digital Ocean roadblocks on this? Is there anything anyone else can do?

**Comment by stancheta** [comment]
Hey Joel, 

I got the map working. It was a change in the mapbox leaflet that caused the problem. If you would like, I can also try deploying it if you could give me access to the droplet.

**Comment by stancheta** [comment]
Geolocation might need some work, however. When I tested it, it was a bit off.

**Comment by joelrip** [comment]
@stancheta: Great! Email me at joel@codeforsacramento.org and I'll send you the login info.

**Comment by stancheta** [comment]
Hey @jesserosato, do you have any documentation from setting up the server? I think I'm running into the same issues that you were running into. I want to know if the server is repair-able or if it would be better to start from scratch. Portion of the error:
```
61078 info install wicit@0.0.1
       61079 info postinstall wicit@0.0.1
       61080 verbose unsafe-perm in lifecycle true
       61081 info wicit@0.0.1 Failed to exec postinstall script
       61082 verbose stack Error: wicit@0.0.1 postinstall: `grunt build`
       61082 verbose stack spawn ENOENT
       61082 verbose stack     at ChildProcess.<anonymous> (/tmp/build/vendor/node/lib/node_modules/npm/lib/utils/spawn.js:17:16)
       61082 verbose stack     at ChildProcess.emit (events.js:98:17)
       61082 verbose stack     at maybeClose (child_process.js:766:16)
       61082 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
       61083 verbose pkgid wicit@0.0.1
       61084 verbose cwd /tmp/build
       61085 error Linux 3.13.0-43-generic
       61086 error argv "/tmp/build/vendor/node/bin/node" "/tmp/build/vendor/node/bin/npm" "install" "--userconfig" "/tmp/build/.npmrc" "--production"
       61087 error node v0.10.46
       61088 error npm  v2.15.1
       61089 error file sh
       61090 error code ELIFECYCLE
       61091 error errno ENOENT
       61092 error syscall spawn
       61093 error wicit@0.0.1 postinstall: `grunt build`
       61093 error spawn ENOENT
       61094 error Failed at the wicit@0.0.1 postinstall script 'grunt build'.
       61094 error This is most likely a problem with the wicit package,
       61094 error not with npm itself.
       61094 error Tell the author that this fails on your system:
       61094 error     grunt build
       61094 error You can get information on how to open an issue for this project with:
       61094 error     npm bugs wicit
       61094 error Or if that isn't available, you can get their info via:
       61094 error
       61094 error     npm owner ls wicit
       61094 error There is likely additional logging output above.
       61095 verbose exit [ 1, true ]
To dokku@XXX.XXX.XXX.XX:wicit
 ! [remote rejected] master -> master (pre-receive hook declined)
```

**Comment by jesserosato** [comment]
@stancheta that certainly looks familiar. Judging by the error it's not able to complete the `grunt build` process which is run automatically after `npm install`. On my local machine, it looks like there's an issue compiling SASS. Clearing out the `node_modules` directory and running `npm install` again seemed to fix it for me, but I'm not sure if that will fix it on the server. I personally have no problem with moving it to another server, but @joelrip and @roughani will probably have more info on how to handle that. Thanks for taking an interest in WICit, and sorry for the delay in getting back to you (and for not having this fixed a long time ago!)

**Comment by stancheta** [comment]
@jesserosato, thanks for taking the time to respond :) and thanks for the input. I was wondering if it was a problem with the actual server itself since documentation on dokku is almost non-existent and the error message was cryptic. I see what I can do on the SASS end but if not, I'll try to see if I can just put the code in a new server.

**Comment by joelrip** [comment]
@stancheta If your attempts at repair don't work, I'm happy to kill this droplet and set up another.

**Comment by stancheta** [comment]
All right. I'll keep you two posted but I probably won't be able to work on it til Monday evening or so.

**Comment by stancheta** [comment]
Works on Heroku: https://wicit.herokuapp.com/#/map

**Comment by stancheta** [comment]
The new server is up and running. Once the domain name has switched to it, I think we can close this issue.

**Comment by joelrip** [comment]
Domain name now points to the new server, and we're up and running again. Thanks for all your work on this @stancheta !
