### ISSUE TITLE
Missing files for dev environment

### ISSUE THREAD

**Issue by codethirteen** [code4sac/wicit#51]
Paul here with Code for Osage. This looks awesome and I am trying to fork this for a local project, as it is super perfect for what we are working on. Unfortunately, I'm running into some errors because it seems `.env.dist` and `package.json` are not included on master branch, and they appear outdated on production branch. Any chance I can grab a copy of the latest version of them?

**Comment by kelfink** [comment]
Hi Paul, we ended up rolling back some changes that were obfuscating code.   May move that forward again later when we've got a better plan, but I believe it should be package complete now.  Sorry this took so long to get back to you.

**Comment by DonaldBrower** [comment]
Hi Paul! We've made some updates to wicit, and the package.json and .env.dist files should be good to go in the master branch. If you check out [This commit](https://github.com/code4sac/wicit/commit/8154fb5e68c82e4bad231c2686b0b914b916a2ff), you'll be able to see how we are loading in the base location data from the California Health and Human Services API. 

You should be able to get a build of wicit up and running by just executing `npm install`, `grunt build`, and `node app.js`, right after cloning the repo. No .env messing around necessary.

**Comment by joelbarker2011** [comment]
I can confirm that you only need to run `npm install` and `node app.js` to get WICit running on http://localhost:3000/ (it's not necessary to run `grunt build`, as this is done in the `postinstall` script).

This issue can be closed, @kelfink.
